name: Run on path1
on:
  push:
    branches:
      - main
    paths:
      - run_path_1
  pull_request:
    branches:
      - main
    paths:
      - run_path_1
jobs:
  list_files:
    name: List file on folder 1
    runs-on: ubuntu-latest

    steps:
      - name: "List files on folder 1"
        run: ls -la run_path_1



