name: Run on path1
on:
  push:
    branches:
      - main
    paths:
      - run_path_2
  pull_request:
    branches:
      - main
    paths:
      - run_path_2
jobs:
  list_files:
    name: List file on folder 2
    runs-on: ubuntu-latest

    steps:
      - name: "List files on folder 2"
        run: ls -la run_path_2



